spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/imobi
        username: postgres
        password: 123456
    jpa:
        hibernate:
            ddlAuto: update
        showSql: true
    
